import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import NavBar from "components/NavBar";
// import { getDataFromTree } from "@apollo/client/react/ssr";
import { PostsDocument, PostsQueryResult, Post } from "generated/graphql";
import { client } from "lib/client";

interface HomePageProps {
  posts: [Post];
}

const Home: NextPage<HomePageProps> = ({ posts }) => {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <div className="max-w-7xl mx-auto p-4 sm:p-6">
        <div>hello world</div>
        {posts.map((item) => (
          <p key={item.id}>{item.title}</p>
        ))}
      </div>
    </>
  );
};

export const getServerSideProps: GetServerSideProps = async () => {
  const { data } = (await client.query({
    query: PostsDocument,
  })) as PostsQueryResult;
  return {
    props: {
      posts: data?.posts,
    },
  };
};

export default Home;
